### ISSUE TITLE
IdM cannot create new users

### ISSUE THREAD

**Issue by flopezag** [flopezag/docker-fiware#7]
The IdM instance is not configured to send emails, therefore the creation of new users should not work properly.

**Comment by flopezag** [comment]
It is needed the installation of the email service and configure the file config.js in order to allow the communication. It is something that should be provided inside the fiware-idm image per se.

**Comment by aarranz** [comment]
HI @flopezag, I recommend you no to think about including an email server inside the fiware-idm image. Email servers are complex services, requiring configuration (especially if they are going to be used on production, so you have to use SSL certificates, creating DKIM keys, ...), setting DNS entries for validation (DKIM, SPF, DMARC ...) and also requiring setting up reverse DNS entries...

The IDM image currently support using an SMTP server, seems fine to me. You can always use a docker container providing an email server (there are several images available on docker hub).

**Comment by flopezag** [comment]
It was resolved with a new image of the IdM.
